#!/usr/bin/env node

var fs = require('fs')
var path = require('path')

var home = process.env['HOME']+'/'

// link files from source
link('./src', home)

// link private files from dropbox
link(home+'Dropbox/dotfiles', home)


function link(srcDir, destDir) {
  if (!fs.existsSync(srcDir))
    return console.log('Skipping', srcDir, '\nSource directory does not exist')
  if (!fs.existsSync(destDir))
    return console.log('Skipping', srcDir, '\nDestination directory does not exist')

  var files
  try {
    files = fs.readdirSync(srcDir)
  } catch(err) {
    return console.error(err)
  }

  files.forEach(function(file) {
    var src = srcDir+'/'+file
    var dest = destDir+'.'+file
    tryLink(src, dest)
  })

}


function tryLink(src, dest) {
  if (fs.existsSync(dest))
    return console.warn('Skipping', src, '\nDestination file already exists.')

  try {
    fs.linkSync(src, dest)
  } catch(err) {
    return console.error(src, '>>', dest, 'ERROR', err)
  }
  return console.log(src, '>>', dest)
}


